require("toady.general-config")
require("toady.general-keymaps")
require("toady.general-plugins")

require("toady.plugin-config.fzf")
require("toady.plugin-config.nvimtree")
require("toady.plugin-config.lspzero")
require("toady.plugin-config.treesitter")
require("toady.plugin-config.colourscheme")
require("toady.plugin-config.autoclosetags")
require("toady.plugin-config.lualine")
require("toady.plugin-config.nvimtsrainbow2")
require("toady.plugin-config.formatter")
require("toady.plugin-config.noice")

require("toady.keymaps.harpoon")
require("toady.keymaps.nvimtree")
require("toady.keymaps.undotree")
require("toady.keymaps.fzf")
